<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal'
        ], function ($, modal) {


        var options = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            title: 'GET OUR EMAIL LETTER',
            buttons: [{
                text: $.mage.__('Continue'),
                class: '',
                click: function () {
                    this.closeModal();
                }
            }]
        };

        var popup = modal(options, $('#elogic-newsletter-popup'));

        $('#elogic-newsletter-popup').modal('openModal');
    })

</script>
