<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Backend\Block\System\Store\Edit $block */

?>
<script type="text/x-magento-init">
{
    "*": {
        "sliderWidget": {
           "template": "#main-slider-wrap",
            "slickOptions": {
                "slidesToShow": 1,
                "dots": true,
                "arrows": false,
                "responsive": [
                    {
                        "breakpoint": 1024,
                        "settings": {
                            "slidesToShow": 1,
                            "infinite": true
                        }
                    },
                    {
                        "breakpoint": 768,
                        "settings": {
                            "slidesToShow": 1
                        }
                    }
                ]
            }
        }
    }
}
</script>
