<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Backend\Block\System\Store\Edit $block */

?>
<script type="text/x-magento-init">
{
    "#main-slider-wrap": {
        "mywidget": {
            "slickOptions": {
            "slidesToShow": 1,
            "dots": true,
            "arrows": false}
        }
    }
}
</script>
