<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Backend\Block\System\Store\Edit $block */

?>

<script type="text/x-magento-init">
{
    "*": {
        "mywidget": {
            "template": ".news-slider",
            "slickOptions": {
                "slidesToShow": 3,
                "responsive": [
                    {
                        "breakpoint": 1200,
                        "settings": {
                            "slidesToShow": 2
                        }
                    },
                    {
                        "breakpoint": 767,
                        "settings": {
                            "slidesToShow": 1
                        }
                    }
                ]
            }
        }
    }
}
</script>
