<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$titleIdHtml = ($block->getTitleId()) ? ' id="' . $block->escapeHtmlAttr($block->getTitleId()) . '"' : '';
$titleClass = ($block->getTitleClass()) ? ' ' . $block->getTitleClass() : '';
$title = $block->getPageTitle();
?>

<div class="page-title-wrapper<?= $block->escapeHtmlAttr($titleClass) ?>">
    <?php if ($block->getViewModel()->getItems()) {?>
        <h1 class="page-title">  <?= __('Your bag is looking good...')?> </h1>
    <?php } else {?>
        <h1 class="page-title">  <?= __('Shopping Bag')?> </h1>
    <?php }?>
    <?= $block->getChildHtml() ?>
</div>
