<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="footer-container">
    <div class="footer-block">
        <h3>about</h3>
        <ul>
            <li>
                <a href="#">News &amp; Stories</a>
            </li>
            <li>
                <a href="#">History</a>
            </li>
            <li>
                <a href="#">Our Studio</a>
            </li>
            <li>
                <a href="#">Showrooms</a>
            </li>
            <li>
                <a href="#">Stocklist</a>
            </li>
        </ul>
    </div>
    <div class="footer-block">
        <h3>customer services</h3>
        <ul>
            <li>
                <a href="#">Contact Us</a>
            </li>
            <li>
                <a href="#">Trade services</a>
            </li>
            <li>
                <a href="#">Login/Register</a>
            </li>
            <li>
                <a href="#">Delivery &amp; Returns</a>
            </li>
            <li>
                <a href="#">FAQs</a>
            </li>
        </ul>
    </div>
    <div class="footer-block">
        <h3>furniture</h3>
        <ul>
            <li>
                <a href="#">Tables</a>
            </li>
            <li>
                <a href="#">Chairs</a>
            </li>
        </ul>
    </div>
    <div class="footer-block">
        <h3>accessories</h3>
        <ul>
            <li>
                <a href="#">Candles &amp; Fragrance</a>
            </li>
            <li>
                <a href="#">Stationery</a>
            </li>
            <li>
                <a href="#">Kitchen &amp; Dining</a>
            </li>
            <li>
                <a href="#">Textiles</a>
            </li>
            <li>
                <a href="#">Gifl Sets</a>
            </li>
        </ul>
    </div>
</div>
