<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

    <div class="footer-sub">
        <ul class="footer-sub-list">
            <li>
                <a href="#">about us</a>
            </li>
            <li>
                <a href="#">blog</a>
            </li>
            <li>
                <a href="#">faqs</a>
            </li>
            <li>
                <a href="#">order tracking</a>
            </li>
            <li>
                <a href="#">contact</a>
            </li>
        </ul>

        <div class="footer-sub-social">
            <span>connect with us:</span>
            <ul>
                <li>
                    <a href="#" class="behance fa fa-behance"></a>
                </li>
                <li>
                    <a href="#" class="facebook fa fa-facebook"></a>
                </li>
                <li>
                    <a href="#" class="google fa fa-google"></a>
                </li>
                <li>
                    <a href="#" class="skype fa fa-skype"></a>
                </li>
                <li>
                    <a href="#" class="twitter fa fa-twitter"></a>
                </li>
            </ul>
        </div>

    </div>

